#
# Run this file using
#
# $ docker-compose up processor
#
version: "3.9"
services:
  mongo:
    image: mongo:4.4.6
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
  pre-commit:
    build:
      context: .
      dockerfile: tests/Dockerfile.pre-commit
    working_dir: /code
    volumes:
    - .:/code
  super-linter:
    image: github/super-linter:v3.15.5
    environment:
    - RUN_LOCAL=true
    - VALIDATE_MARKDOWN=false
    - VALIDATE_PYTHON_ISORT=false
    - VALIDATE_XML=false
    - VALIDATE_NATURAL_LANGUAGE=false
    - IGNORE_GITIGNORED_FILES=true
    volumes:
    - .:/tmp/lint/
    - ./tox.ini:/action/lib/.automation/.flake8
  # This container will run successfully
  # only if all dependencies return no errors.
  test:
    image: python:3.9-slim
    environment:
      TEST_MONGODB_URI: "mongodb://root:secret@mongo:27017"
    depends_on:
    - mongo
    working_dir: /code
    volumes:
    - .:/code
    command: >-
      bash -c 'pip install tox && tox'
