# Run the SuperLinter action with some custom setup.

name: Lint

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - "ISSUE_TEMPLATE/**"
      - "README.md"
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - "ISSUE_TEMPLATE/**"
      - "README.md"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Super-Linter
        uses: github/super-linter@v3.15.5
        env:
          VALIDATE_MARKDOWN: false
          # Disabled for conflicts with the isort version used in pre-commit
          #   you can re-enable it if you align your local isort with
          #   the one in the super-linter image.
          VALIDATE_PYTHON_ISORT: false
          VALIDATE_XML: false
          VALIDATE_NATURAL_LANGUAGE: false

  test-pre-commit:
    runs-on: ubuntu-latest
    # Only "fat" python images have git installed.
    container: python:3.9
    steps:
      - uses: actions/checkout@v3

      - name: Run commit hooks.
        run: |
          pip3 --no-cache-dir install pre-commit
          git config --global --add safe.directory $PWD
          pre-commit install
          pre-commit run -a

      # Store (expiring) logs on failure.
      # Retrieve artifacts via `gh run download`.
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: pre-commit.log
          path: /github/home/.cache/pre-commit/pre-commit.log
          retention-days: 5
